### ISSUE TITLE
MIssing styles when showing stored contnet on resource details page.

### ISSUE THREAD

**Issue by reppair** [ek0519/nova-quilljs#21]
Consider these.. 

![Screenshot from 2021-06-11 14-50-43](https://user-images.githubusercontent.com/10784954/121682264-89d88000-cac4-11eb-8e44-a1e0ed25031b.png)

How can I add styles for the indented, centered and right aligned texts or overwrite the `.ql-indent-x` & `.ql-align-x` classes?

In the front-end I just targeted a parent class `quill` and then in it `.ql-indent-x` etc.. but in Nova, that is not an option.

Maybe If a create a custom field to extend this one, I can add my styles? Doesn't seem like the right way to go about it though...

**Comment by reppair** [comment]
I ended up making custom `DetailsField` and showing mine instead of the one provided by the package.. the only difference is:

```css
<style>
.markdown p, .markdown blockquote, .markdown ol, .markdown ul {
    margin-top: 0;
    margin-bottom: .5rem;
}
.ql-indent-1 {
    margin-left: 1rem;
}
.ql-indent-2 {
    margin-left: 2rem;
}
.ql-indent-3 {
    margin-left: 3rem;
}
.ql-indent-4 {
    margin-left: 4rem;
}
.ql-indent-5 {
    margin-left: 5rem;
}
.ql-align-center {
    text-align: center;
}
.ql-align-right {
    text-align: right;
}
.ql-video {
    width: 800px;
    height: 450px;
}
</style>
```
